[package]
name = "rdns"
version = "0.1.0"
authors = ["Aaron Eline <aeline@umd.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.4"
nom = "6.0.0-alpha1"
